package telesat

import "time"

func mockPerformanceReports() []PerformanceReport {
	baseTime := time.Date(2028, 3, 22, 0, 0, 0, 0, time.UTC)
	return []PerformanceReport{
		{
			ID:             "pr-001",
			SubscriptionID: "sub-001",
			ReportPeriod:   "1hour",
			StartTime:      baseTime,
			EndTime:        baseTime.Add(1 * time.Hour),
			Status:         "complete",
			Metrics: PerformanceMetrics{
				AvgLatencyMs:      24.2,
				MaxLatencyMs:      31.8,
				MinLatencyMs:      22.1,
				AvgJitterMs:       2.3,
				MaxJitterMs:       5.1,
				PacketLossPct:     0.002,
				AvgThroughputMbps: 487.0,
				MaxThroughputMbps: 500.0,
				AvailabilityPct:   100.0,
				SNRdB:             18.5,
				BeamHandovers:     4,
				ISLReroutes:       0,
			},
		},
		{
			ID:             "pr-002",
			SubscriptionID: "sub-001",
			ReportPeriod:   "1hour",
			StartTime:      baseTime.Add(1 * time.Hour),
			EndTime:        baseTime.Add(2 * time.Hour),
			Status:         "complete",
			Metrics: PerformanceMetrics{
				AvgLatencyMs:      26.7,
				MaxLatencyMs:      62.3,
				MinLatencyMs:      22.5,
				AvgJitterMs:       4.8,
				MaxJitterMs:       12.1,
				PacketLossPct:     0.04,
				AvgThroughputMbps: 472.0,
				MaxThroughputMbps: 500.0,
				AvailabilityPct:   99.97,
				SNRdB:             16.2,
				BeamHandovers:     7,
				ISLReroutes:       2,
			},
		},
		{
			ID:             "pr-003",
			SubscriptionID: "sub-002",
			ReportPeriod:   "1hour",
			StartTime:      baseTime,
			EndTime:        baseTime.Add(1 * time.Hour),
			Status:         "complete",
			Metrics: PerformanceMetrics{
				AvgLatencyMs:      22.8,
				MaxLatencyMs:      28.4,
				MinLatencyMs:      20.9,
				AvgJitterMs:       1.9,
				MaxJitterMs:       4.2,
				PacketLossPct:     0.001,
				AvgThroughputMbps: 940.0,
				MaxThroughputMbps: 1000.0,
				AvailabilityPct:   100.0,
				SNRdB:             19.1,
				BeamHandovers:     3,
				ISLReroutes:       0,
			},
		},
		{
			ID:             "pr-004",
			SubscriptionID: "sub-002",
			ReportPeriod:   "24hour",
			StartTime:      baseTime.Add(-24 * time.Hour),
			EndTime:        baseTime,
			Status:         "complete",
			Metrics: PerformanceMetrics{
				AvgLatencyMs:      23.1,
				MaxLatencyMs:      35.6,
				MinLatencyMs:      20.2,
				AvgJitterMs:       2.4,
				MaxJitterMs:       7.8,
				PacketLossPct:     0.008,
				AvgThroughputMbps: 912.0,
				MaxThroughputMbps: 1000.0,
				AvailabilityPct:   99.99,
				SNRdB:             18.8,
				BeamHandovers:     72,
				ISLReroutes:       3,
			},
		},
	}
}
